# Generated by Django 5.2.7 on 2026-01-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_encrypted', models.BinaryField()),
                ('email_encrypted', models.BinaryField()),
                ('phone_encrypted', models.BinaryField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(to='specialist.symptom'),
        ),
    ]
