# Generated by Django 5.2.7 on 2026-01-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='specialist.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(related_name='patients', to='specialist.symptom'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
